[package]
name = "remotefs-aws-s3"
version = "1.0.0"
authors = ["Christian Visintin <christian.visintin@veeso.dev>"]
categories = ["network-programming"]
documentation = "https://docs.rs/remotefs-aws-s3"
edition = "2024"
homepage = "https://github.com/remotefs-rs/remotefs-rs-aws-s3"
include = ["src/**/*", "LICENSE", "README.md", "CHANGELOG.md"]
keywords = ["remotefs", "s3-client"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/remotefs-rs/remotefs-rs-aws-s3"
rust-version = "1.94.1"
description = "remotefs Aws S3 client library"

[dependencies]
aws-config = "1"
aws-credential-types = "1"
aws-sdk-s3 = { version = "1", default-features = false, features = ["default-https-client", "http-1x", "rt-tokio", "sigv4a"] }
aws-smithy-types = { version = "1", features = ["byte-stream-poll-next"] }
bytes = "1"
futures-io = "0.3"
log = "0.4"
remotefs = { version = "1", features = ["async"] }
tokio = { version = "1", features = ["rt"] }

[dev-dependencies]
env_logger = "0.11"
futures = "0.3"
pretty_assertions = "1"
rand = "0.10"
testcontainers = "0.28"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "time"] }

[features]
default = ["find"]
# misc
find = ["remotefs/find"]
no-log = ["log/max_level_off"]
tokio = ["remotefs/tokio"]
# tests
with-containers = []
with-s3-ci = []

[target."cfg(target_os = \"windows\")"]
[target."cfg(target_os = \"windows\")".dependencies]
path-slash = "0.2"
